apiVersion: v2
appVersion: v18.8.5
dependencies:
- name: gitlab
  repository: ""
  version: '*.*.*'
- name: certmanager-issuer
  repository: ""
  version: '*.*.*'
- name: minio
  repository: ""
  version: '*.*.*'
- name: registry
  repository: ""
  version: '*.*.*'
- alias: certmanager
  condition: installCertmanager
  name: cert-manager
  repository: https://charts.jetstack.io/
  version: v1.17.4
- condition: gitlab-runner.install
  name: gitlab-runner
  repository: https://charts.gitlab.io/
  version: 0.85.0
- condition: nginx-ingress.enabled
  name: nginx-ingress
  repository: ""
  version: '*.*.*'
- alias: nginx-ingress-geo
  condition: nginx-ingress-geo.enabled
  name: nginx-ingress
  repository: ""
  version: '*.*.*'
description: GitLab is the most comprehensive AI-powered DevSecOps Platform.
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
keywords:
- gitlab
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: gitlab
sources:
- https://gitlab.com/gitlab-org/charts/gitlab
version: 9.8.6
