# MinIO 配置 - 官方 minio/minio chart

mode: standalone

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2024-12-18T13-15-44Z
  pullPolicy: IfNotPresent

rootUser: "admin"
rootPassword: "admin12345"

replicas: 1

persistence:
  enabled: true
  size: 10Gi

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

minioAPIPort: "9000"
minioConsolePort: "9001"
